# docker-compose.yml
version: '3'
services:
  flask:
    image: webapp-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - $HOME/.aws:/home/aws:ro
    ports:
      - "8080:8080"
    network_mode: host
  nginx:
    image: webapp-nginx
    container_name: nginx
    environment:
      - SERVER_NAME=0.0.0.0
    build:
      context: .
      dockerfile: Dockerfile-nginx
    restart: always
    network_mode: host
#    ports:
#      - 8080:80
#    depends_on:
#      - flask